api_platform:
    title: 'API REST Receipts'
    description: 'API for educational project YNOV - Pierre Coeffeteau'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
